name: 'Setup Mock-Firebolt'
description: 'Sets up Mock-Firebolt and caches it.'
runs:
  using: "composite"

  steps:
    - name: Generate Dependency Hash Key
      id: cache-key
      shell: bash
      run: echo "hash=$( ( echo "${{ env.MOCK_SHA1SUM }}"; sha256sum "${{ env.MOCK_PATCH }}" ) | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: Restore Dependency Cache
      uses: actions/cache@v4
      id: cache-restore
      with:
        path: ${{ env.MOCK_PATH }}
        key: ${{ runner.os }}-mock-${{ steps.cache-key.outputs.hash }}

    - name: Build and Install Mock-Firebolt
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Building Mock-Firebolt..."
        git clone --depth 1 --branch main https://github.com/rdkcentral/mock-firebolt.git ${{ env.MOCK_PATH }}
        cd ${{ env.MOCK_PATH }}
        git fetch --shallow-since=2025-11-01
        git checkout ${{ env.MOCK_SHA1SUM }}
        git apply "${{ env.MOCK_PATCH }}"
        cd server
        npm ci
        echo "Mock-Firebolt built and installed to ${{ env.MOCK_PATH }}"

    - name: Cache Save Confirmation
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: echo "New dependency cache will be saved."

outputs:
  deps_cache_key:
    description: "The cache key for the dependencies."
    value: ${{ steps.cache-key.outputs.hash }}
