name: Clone Repository

on:
  workflow_dispatch:
  push:
    branches-ignore: [ main ]
  pull_request:
    types:
      - opened
    branches: [ main ]
env:
  HUSKY: 0

jobs:
  release:
    name: Run Mfos Jpb
    runs-on: ubuntu-latest
    steps:
      - name: Clone Mfos
        uses: actions/checkout@v2
        with:
          repository: rdkcentral/mock-firebolt
          ref: main
      - name: Install MFOS Dependencies
        run: |
          cd server
          cp src/.mf.config.SAMPLE.json src/.mf.config.json
          npm install
          npm start &
          cd ..//..
          ls 