name: Clone Repository

on:
  workflow_dispatch:
  push:
    branches-ignore: [ main ]
  pull_request:
    types:
      - opened
    branches: [ main ]
env:
  HUSKY: 0

jobs:
  release:
    name: Run Mfos Job
    runs-on: ubuntu-latest
    steps:
      - name: FCA Standalone Report
        run: |
          PR_BRANCH=$(echo "${{ github.event_name }}" | tr '[:upper:]' '[:lower:]')
          
          if [ "${PR_BRANCH}" == "pull_request" ]; then
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          elif [ "${PR_BRANCH}" == "push" ]; then
          PR_BRANCH="${{ github.ref }}"
          PR_BRANCH="${PR_BRANCH#refs/heads/}"
          else
          echo "Unsupported event: ${{ github.event_name }}"
          exit 1
          fi
          echo "Pull Request Branch: ${PR_BRANCH}"
          git clone --branch ${{ PR_BRANCH }} https://github.com/rdkcentral/firebolt-apis.git
          ls 
          git clone https://github.com/rdkcentral/mock-firebolt.git
          cd mock-firebolt/server
          cp src/.mf.config.SAMPLE.json src/.mf.config.json
          npm install
          npm start &
          echo "Sleep 10s"
          sleep 10s
          cd ..//..
          ls 
          echo "LS AFTER MOCK"
          git clone https://github.com/rdkcentral/firebolt-certification-app.git
          cd firebolt-certification-app
          npm install
          npm start &
          sleep 10s
          cd ..
          echo "LS AFTER FCA"
          ls