name: Clone Repository

on:
  workflow_dispatch:
  push:
    branches-ignore: [ main ]
  pull_request:
    types:
      - opened
    branches: [ main ]
env:
  HUSKY: 0

jobs:
  release:
    name: Run Mfos Job
    runs-on: ubuntu-latest
    steps:
      - name: FCA Standalone Report
        run: |
          apt-get update && apt-get -y install jq
          PR_BRANCH=$(echo "${{ github.event_name }}" | tr '[:upper:]' '[:lower:]')
          if [ "${PR_BRANCH}" == "pull_request" ]; then
            PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          elif [ "${PR_BRANCH}" == "push" ]; then
            PR_BRANCH="${{ github.ref }}"
            PR_BRANCH="${PR_BRANCH#refs/heads/}"
          else
            echo "Unsupported event: ${{ github.event_name }}"
            exit 1
          fi
          git clone --branch ${PR_BRANCH} https://github.com/bpvstaty366/firebolt-apis.git
          cd firebolt-apis
          npm i
          npm run compile
          cd ..
          git clone https://github.com/rdkcentral/mock-firebolt.git
          cd mock-firebolt/server
          cp ../../firebolt-apis/dist/firebolt-open-rpc.json ../../mock-firebolt/server/src/firebolt-open-rpc.json
          jq 'del(.supportedOpenRPCs[] | select(.name == "core"))' src/.mf.config.SAMPLE.json > src/.mf.config.SAMPLE.json.tmp && mv src/.mf.config.SAMPLE.json.tmp src/.mf.config.SAMPLE.json
          jq '.supportedOpenRPCs += [{"name": "core","cliFlag": null,"cliShortFlag": null,"fileName": "firebolt-open-rpc.json","enabled": true}]' src/.mf.config.SAMPLE.json > src/.mf.config.SAMPLE.json.tmp && mv src/.mf.config.SAMPLE.json.tmp src/.mf.config.SAMPLE.json
          cat src/.mf.config.SAMPLE.json
          cp src/.mf.config.SAMPLE.json src/.mf.config.json
          npm install
          npm start &
          cd ..//..
          git clone https://github.com/rdkcentral/firebolt-certification-app.git
          cd firebolt-certification-app
          npm install
          npm start &
          cd ..
          echo "LS AFTER FCA"
          ls