name: Clone Repository

on:
  workflow_dispatch:
  push:
    branches-ignore: [ main ]
  pull_request:
    types:
      - opened
    branches: [ main ]
env:
  HUSKY: 0

jobs:
  release:
    name: Run Mfos Job
    runs-on: ubuntu-latest
    steps:
      - name: FCA Standalone Report
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | awk -F '/' '{print $NF}')" >> $GITHUB_ENV
          git clone --branch ${{ env.BRANCH_NAME }} https://github.com/rdkcentral/firebolt-apis.git
          ls 
          git clone https://github.com/rdkcentral/mock-firebolt.git
          cd mock-firebolt/server
          cp src/.mf.config.SAMPLE.json src/.mf.config.json
          npm install
          npm start &
          echo "Sleep 10s"
          sleep 10s
          cd ..//..
          ls 
          echo "LS AFTER MOCK"
          git clone https://github.com/rdkcentral/firebolt-certification-app.git
          cd firebolt-certification-app
          npm install
          npm start &
          sleep 10s
          cd ..
          echo "LS AFTER FCA"
          ls