name: Artifact

on:
  workflow_run:
    workflows: [Standalone]
    types:
      - completed

jobs:
  RunStandaloneTest:
    runs-on: ubuntu-latest
    steps:
      - name: Get an open-rpc from firebolt-apis
        run: |
          apt-get update && apt-get -y install jq curl
