name: Artifact

on:
  workflow_run:
    workflows: [ "Standalone" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts Link
        run: |
          echo "HI"
