name: 'Setup apt Dependencies'
description: 'Sets up the apt dependencies and caches them.'
runs:
  using: "composite"
  steps:
    - name: Ensure apt cache is writable
      shell: bash
      run: |
        sudo chmod -R a+rw /var/cache/apt/archives

    - name: Cache apt packages
      id: cache-apt
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/actions/setup-apt-deps/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-cache-

    - name: Install apt dependencies
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          libboost-all-dev \
          cmake \
          jq

    - name: Ensure apt cache is readable
      shell: bash
      run: |
        sudo chmod -R a+r /var/cache/apt/archives