name: 'Setup apt Dependencies'
description: 'Sets up the apt dependencies and caches them.'
runs:
  using: "composite"
  steps:
    - name: Cache apt packages
      id: cache-apt
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-cache-${{ hashFiles(format('{0}/action.yml', github.action_path)) }}

    - name: Install apt dependencies
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          libboost-all-dev \
          cmake \
          jq